### ISSUE TITLE
rewrite PopupWindow

### ISSUE THREAD

**Issue by PascalLuginbuehl** [pamapa/oidc-client-ts#29] opened 2021-08-09 09:57 UTC
Code could be a lot simpler. Would fix a lot of ts and linting errors

**Comment by PascalLuginbuehl** [comment] 2021-08-17 06:16
Currently there is a bug where popupwindow no longer closes. This has to do with #31

**Comment by pamapa** [comment] 2021-09-15 11:35
we should port the code to make use of `postMessage`

**Comment by pamapa** [comment] 2021-09-15 13:55
duplicate of #31

**Closed by pamapa** 2021-09-15 13:55 UTC
Labels: duplicate
